# Generated by Django 5.2.7 on 2025-10-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('category', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('desc', models.TextField()),
            ],
        ),
    ]
